project:
  title: "1期_slides"
subtitle: "佐久間ゼミ　1期"
author: 
  - name: "佐久間 智広"
    affiliation: "Kobe University"
    email: "sakuma@port.kobe-u.ac.jp"
date: 2023/04/11
date-format: YYYY/MM/DD
format: 
  revealjs:
    width: 1280
    height: 1024
    slide-number: true
    preview-links: auto
    logo: kobe.png
    css: logo.css
    footer: "ゼミ"
    smaller: false
    scrollable: true
    theme: [white,fonts.scss]
    fig-cap-location: bottom
    tbl-cap-location: top
    embed-resources: false
    number-sections: true
    chalkboard: true
    number-depth: 2
    toc: true
    toc-depth: 1
    navigation-mode: vertical
  pptx:
    slide-number: true
editor: visual
bibliography: references.bib
csl: the-accounting-review.csl
include-after-body: header.html